name: test build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clean
      run: make clean
      working-directory: ./src
    - name: make
      run: make
      working-directory: ./src
